I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 32, in script
    f "我们是不是在哪见过？"
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
  File "game/script.rpy", line 19, in execute
    screen Pts:
  File "game/script.rpy", line 19, in execute
    screen Pts:
  File "game/script.rpy", line 20, in execute
    text "一糖 [pts] 羁绊 [link]" xpos 0.87 ypos 0.106
NameError: Name 'pts' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 32, in script
    f "我们是不是在哪见过？"
  File "renpy/ast.py", line 889, in execute
    statement_name(stmt_name)
  File "renpy/ast.py", line 47, in statement_name
    i(name)
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
  File "renpy/exports.py", line 1653, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "renpy/display/core.py", line 2801, in do_with
    clear=clear)
  File "renpy/display/core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs) # type: ignore
  File "renpy/display/core.py", line 3804, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "renpy/display/core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 582, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/screen.py", line 451, in visit_all
    callback(self)
  File "renpy/display/core.py", line 3804, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "renpy/display/screen.py", line 462, in per_interact
    self.update()
  File "renpy/display/screen.py", line 653, in update
    self.screen.function(**self.scope)
  File "game/script.rpy", line 19, in execute
    screen Pts:
  File "game/script.rpy", line 19, in execute
    screen Pts:
  File "game/script.rpy", line 20, in execute
    text "一糖 [pts] 羁绊 [link]" xpos 0.87 ypos 0.106
  File "renpy/text/text.py", line 1678, in _scope
    return self.set_text(self.text_parameter, scope, self.substitute, update)
  File "renpy/text/text.py", line 1702, in set_text
    i, did_sub = renpy.substitutions.substitute(i, scope, substitute)
  File "renpy/substitutions.py", line 278, in substitute
    s = formatter.vformat(s, (), kwargs) # type: ignore
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 585, in _vformat
  File "renpy/substitutions.py", line 168, in get_field
    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 605, in get_value
  File "renpy/substitutions.py", line 236, in __getitem__
    raise NameError("Name '{}' is not defined.".format(key))
NameError: Name 'pts' is not defined.

Windows-10-10.0.19041 AMD64
Ren'Py 7.5.1.22070801
因缘和合 1.0
Sat Aug 12 03:06:29 2023
